apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sonarr.local.khider.fr-cert
  namespace: media
spec:
  secretName: sonarr-cert
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
  dnsNames:
    - sonarr.local.khider.fr
    - sonarr.khider.fr
