# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/library/common/values.schema.json

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  interval: 10m
  install:
    createNamespace: true
  chart:
    spec:
      chart: app-template
      version: 5.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    nameOverride: sonarr-prod

    controllers:
      sonarr:
        containers:
          main:
            image:
              repository: ghcr.io/linuxserver/sonarr
              tag: 4.0.17.2952-ls312
            env:
              PUID: "1000"
              PGID: "1000"
    
    defaultPodOptions:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
          
    persistence:
      config:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 3Gi
      media:
        type: nfs
        server: nas.local.khider.fr
        path: /volume1/Jellyfin
        globalMounts:
          - path: /data
          
    service:
      main:
        controller: sonarr
        ports:
          http:
            port: 8989
 
    ingress:
      main:
        enabled: false
