---
services:
  mariadb:
    image: ghcr.io/linuxserver/mariadb:11.8.8
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./deployment:/config
    ports:
      - 3306:3306
    restart: unless-stopped
