apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - config-pvc.yaml
  - helm-release.yaml
  - ingressroute.yaml
  - backup-schedule.yaml
  - network-policy.yaml
