---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: arc-pat-secret
  namespace: arc-runners
spec:
  encryptedData:
    github_token: AgCdY8pokrFZK8f9RvFM4CapuOx6D6FcYKLfjp6+QHp15W7UIxKxtjzLLbh8Wt8iOpP2moFt3hv1qwVkNxmsBR1EYWQ607N5vJgobptdADI6VuylqPmnj9ZjkH0xVzoX6HJ6eCmUe41cSIJEEz82ILPqhJjws3ffU+m4mFzhgKPDCJNnG5I2kSppe9YhKIEqH4i2xZSXeKTH0ua4rm5G2IjAq+U+vVEuoCN1AUXzvXN+O9TuwIkHgHk+5PI6h3NME7SA95wja41oQcc6YZteYsqig+ajvNDmQs3KeYiMHgTNyY3sdpLFpxeYzp3bajtqQ/4cXV90XZPmdncAIBysPPbEP6Wvot35xAJumrsFNOV6AAyf2CN8ByV7sheuzMbqLpa5sf5tJ2pR77Q4P4XPpZasSmFVITMvfrB7NRuvhOOnFJHeSwsgF0kZMGfAy2BlC69pMnfs+mLJ+o34BjL3oP8lo0rx9vyEm18garjNPPRRO2kbZbEqCmYVqb/20UjQwuOvBmEB+VVnjuy6ooKNdJ2Z/jMfEzlA8eq+4CRNMj85n7JNaMECfH9W/MiMYU61Sg3ltgzq3OoPG3RHmnWe3FH0qu4A4DT3+1uZ/TMBmEpc8LyI+KPQjALbz9mD6/nhctditwr6NuePGWOHqaMCVlntw4KqzLwjsdOe7rovzwjh0KQoQdeSqmb+qlzEq3++3mbKA7+z//xVgDa9Ee/Ph5OGoSV1O806Kq8zk7QPKSH/beOl5/0Lfh7g
  template:
    metadata:
      name: arc-pat-secret
      namespace: arc-runners
