apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bjw-s-charts
  namespace: flux-system
spec:
  interval: 1h
  url: https://bjw-s-labs.github.io/helm-charts/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik-repository
  namespace: traefik
spec:
  interval: 1h
  url: https://traefik.github.io/charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cilium-repository
  namespace: kube-system
spec:
  interval: 1h
  url: https://helm.cilium.io/
