# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/library/common/values.schema.json

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: n8n
spec:
  interval: 10m
  install:
    createNamespace: true
  chart:
    spec:
      chart: app-template
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  values:
    controllers:
      n8n:
        containers:
          main:
            image:
              repository: docker.n8n.io/n8nio/n8n
              tag: 2.38.3
            env:
              N8N_HOST: n8n.local.khider.fr
              N8N_PORT: "5678"
              N8N_PROTOCOL: https
              N8N_EDITOR_BASE_URL: https://n8n.local.khider.fr/
              WEBHOOK_URL: https://n8n.local.khider.fr/
              N8N_PROXY_HOPS: "1"
              N8N_RUNNERS_ENABLED: "true"
              GENERIC_TIMEZONE: Europe/Paris
              TZ: Europe/Paris

    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault

    persistence:
      data:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 5Gi
        globalMounts:
          - path: /home/node/.n8n

    service:
      main:
        controller: n8n
        ports:
          http:
            port: 5678

    ingress:
      main:
        enabled: false
