apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingressroute-grafana.yaml
  - ingressroute-prometheus.yaml
  - ingressroute-alertmanager.yaml
  - ingressroute-public-dashboard.yaml
