apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backup-schedule.yaml
  - helm-release.yaml
  - helm-repository.yaml
  - namespace.yaml
  - nextcloud-ingress.yaml
  - remoteip-configmap.yaml
  - sealed-secret.yaml
