# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/library/common/values.schema.json

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: khider-fr
  namespace: web
spec:
  interval: 10m
  install:
    createNamespace: true
  chart:
    spec:
      chart: app-template
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    nameOverride: khider-fr-prod

    controllers:
      khider-fr:
        replicas: 2
        containers:
          main:
            image:
              repository: ghcr.io/tkhider/khider.fr
              tag: latest@sha256:6baae3b3499fc86d2c4141c0d4f6f5a0e5ff63c2bb4834369395c2c04a99f8e2
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                  - ALL
                add:
                  - CHOWN
                  - SETUID
                  - SETGID
                  - NET_BIND_SERVICE
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 128Mi

    defaultPodOptions:
      securityContext:
        seccompProfile:
          type: RuntimeDefault

    service:
      main:
        controller: khider-fr
        ports:
          http:
            port: 80

    ingress:
      main:
        enabled: false
