---
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:34.0.3
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./deployment/config:/config
      - ./deployment/nextcloud/:/data
    ports:
      - 9344:443
    restart: unless-stopped
