---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: qbittorrent-vpn
  namespace: downloads
spec:
  encryptedData:
    OPENVPN_PASSWORD: AgAeFZrVQUjgXQ/hFIX5c8PVBgyWPlYd09obSVbomdzje6wjsQjdVI/vS29esvwiZZqqXZx99W4DRPteW6qajBV6c1pzQ+1HaZnsP5w13ZRVdMb1nQlpXtAvM8fVFM87cY88vbD8DO2/jMxuOKZqG78ho8Pt9JQ54LwjKsYeNc+fWgE2upuIQcBVg9w6tV1Foi3s9EEGNo3oZJ9Pa7NSj0MRXBTjOtT5qsibuTUAtR9B1UgkYv1MHy+miLo0/xk7BYrJV/mKkKEHQecR/CmAXT6ZLRWzdSOLSO8aWgOjkBchp3zL3kHY5vRW+a7H6Plie3YC+z5DRRZFgiXHNCtlslPAJ9GRBmcxd3r5FJGFcfZApCG/jI1OUkRyxHovVwXfgqaWrMpmPaMLo7+akTccMqiar5he72C4HXtyG/cst2irfSLe6UuejKjoKmzv1ubHYssSmLvx/jHfNB4jMWHfUPiO3l4eiBFj5vN2nCpMwdfLp70NvH4J2eCBOEz+URakuFp5ZLXPAzjiAw4ECgCa9ZLyrVGdTUXXm8cRHRG22GQrUxwm3yEKcpxZ/ftlNf2kYqPUnjq5gaitB1AFwNAN4StctFR9h05Yv2EBam8pYU6ipOZueG76ASdZvUqoOVmEhHbI9I1VuJIOR23TAojVCJr1QsSRS5dSYX8LPZbV8rV/NoKSeHDa+/CDcgeghBQOXsSed8CIqvtNiYnXyRKjYmhyXvKlVzPRbXQ=
    OPENVPN_USER: AgAa8/g81WMxZ8Bnp335q4AOGk/+mrbkDjW/nZJu9l1R4pKJ/xB4ELld1q1A1kALN0TzZ4YWXEDm5gzul9B0kO8e9kHKLdqv43qEz9DYY4OeiaGC6/UbEEguRvXk9w8o3ecDAJTr+LEaRp4pFoTZ/5VaVro0dCXssI4gVTVmqvk3NR0bix3RTQGFYwKb5nmxWRrPnMlGy5Ndn3OVF00cPrxKZiZKwACfShIoI/I+qbPMMDj4/JWo5p4RW9dBk17zDEQbic1SC4zSDdBt8fM5NjiubMXoIyaPC/7PQyO48GHF7vbGP6FFi2LZ+18UWXdA7scxDm6gN8qy96Dvm91sCoUp5e7ol/LVmxMaUOpr1Q/1v1UqBh10j3qwpF9eBh2nw9c6bYmhfdYCDzrc6hVnb/cpCHSMGc/KBEVVcz0qYlgXuqQbOskKbKzx8uWAmefBPc5WI1J3HDAYl3tPNJDJcvR2799/fNPEtjE5WThtw4FSEz8wimQ2WFuhOzmHIbbjS82eF9KUTSZSFqhsXQcOn10X/WK2H5jZyD8e9+Li5tKf6lUvQvWYPr91rGBwWcqOZE3kdOesHZu423kW8sCd8HDyFeZXTJ8/A2xvrMSOEcXAwit62q66cml0c4iPFNrszGdhOcdR2ttyKzsBy6nbqYf7F/A/t0fWJHM9pqtpUTt2t871yuArAY9hdEF2EJOwZvF508qM0Q2m30V7a/vkQXHJSahT9H1FqPU=
  template:
    metadata:
      name: qbittorrent-vpn
      namespace: downloads
