apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: velero
      version: 12.1.0
      sourceRef:
        kind: HelmRepository
        name: velero-repository
      interval: 5m
  releaseName: velero
  install:
    createNamespace: true
    remediation:
      retries: 3
  values:
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.14.2
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
    credentials:
      useSecret: true
      existingSecret: velero-r2-credentials
    configuration:
      features: EnableCSI
      defaultSnapshotMoveData: true
      backupStorageLocation:
        - name: default
          provider: aws
          bucket: velero-backup
          default: true
          config:
            region: auto
            s3ForcePathStyle: "true"
            s3Url: https://b3feeccbd92acbd9415cb3add60d6826.r2.cloudflarestorage.com
            checksumAlgorithm: ""
    snapshotsEnabled: false
    deployNodeAgent: true
    nodeAgent:
      extraArgs:
        - --node-agent-configmap=node-agent-config
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: kube-prometheus-stack
