---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    token: AgAyS2ydjLqr0apU4nbXrj2V/uhIdsAaxkfLeqvWRWcszHx1/BnklVJ9xoAdQQnwau+G9HXNB/otpHz/RZSPxfJUzOM1SUPSAyRhOumYuL/aOWEXqis3Z4dNhBxwAsL8zZ6Cwthw+F8OQCMtU4Jas9A5iy4CD9bLwuF31jwewN/a6b+NnHA5TmNn+pl/ygN6/08mYowdAAxe2qnwhYl/j9UU5Awqw1t8DIteXThvgxHr0xVyTnIIiLA2KHtapMWjeMqW9Klxa0SguOU232Gwmu1/4MdeRthxtIM9134cnI9wM0JYdAMZXj83stRrxRkY3RdWa4y28wSA6XT/Z5Onwz8mwzuTP2/3QBeAJBqBPUqIZTfDQi5kNLh8a03rbrJ7FGJoWbeUF17wi1FDMWnpNUBsp3nn2/T8uhDyIaayBofQXuTT5NxTLo81/A/9ndq/XDNB02w7UL/uw9+5uPy+6CbvJboeKoCeFsKaVgpwKCV3knh4lVzcl57q859sQ/h7jjatEjADirJPpNPnXhh1YRhdhkOO4rYHq/w/0vMImi9Y3Sg6DJ4Otbz0Lx+ccl+PAfM/OUZdTKJ5R/rcoj8nqFpZdPwEvPpxKQ3DoY00TGEeAr+24tCBRsRqzTEFjxXyW8mVwVQ6IMFZERnkvwJ/SIEiq4dzuPkoZyU8jvhBOfOYSx4DmqP72oyXquA0n0pENGdUZQUjH40nUPpKZp7Ehbc63X7qzgw9uDGkxDbdhXVxVcID/iBCw1FoHWOQNWQQPMvb21/+3vKsE0snbdcdrfqHrrkfkne4rTPmlXYM0EYyUDlfM8m8OOPRnpTC0G9qmul9hdWqfW/l3jQHzgKIeWqQwClXguKaBFT6vA674Yw3N2Di6dqN1AkML03aiEsrYzTenYRWYtcJ76MpLdLL3QXr80FVYo8W6r1VSBA2g5DauhI2/5ZorC6H
  template:
    metadata:
      name: cloudflare-tunnel-token
      namespace: cloudflare-tunnel
