name: Ansible Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'ansible/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'ansible/**'

jobs:
  deploy:
    runs-on: arc-runner-set
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add Hosts to known_hosts
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          touch ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Validate Playbook
        run: |
          cd ansible
          ansible-playbook -i inventory.ini deploy-homelab.yml --syntax-check

      - name: Run Playbook
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'False'
        run: |
          cd ansible
          ansible-playbook -i inventory.ini deploy-homelab.yml
